# Generated by Django 4.0.6 on 2023-02-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
    ]
